version: "3"

services:
  postgresql:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=teste
      - POSTGRESQL_PASSWORD=teste123
      - POSTGRESQL_DATABASE=api-teste
